export const mockContacts = [
  {
    id: '1',
    name: 'User1',
    avatar: 'U1',
    lastMessage: 'See you at the meeting!',
    time: '2m',
    unread: 2,
    online: true,
  },
  {
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },
  {
    id: '4',
    name: 'Marcus Rodriguez',
    avatar: 'MR',
    lastMessage: 'Perfect! I\'ll send it over.',
    time: '5h',
    online: true,
  },
  {
    id: '5',
    name: 'Emily Watson',
    avatar: 'EW',
    lastMessage: 'Great work on the presentation',
    time: '1d',
    online: false,
  },
  {
    id: '6',
    name: 'David Kim',
    avatar: 'DK',
    lastMessage: 'Let me check and get back to you',
    time: '1d',
    online: false,
  },
  {
    id: '7',
    name: 'Lisa Anderson',
    avatar: 'LA',
    lastMessage: 'Sure thing!',
    time: '2d',
    online: true,
  },
  {
    id: '8',
    name: 'James Taylor',
    avatar: 'JT',
    lastMessage: 'Looking forward to it',
    time: '3d',
    online: false,
  },
  {
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },{
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },{
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },{
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },{
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },{
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },{
    id: '2',
    name: 'Another User',
    avatar: 'AU',
    lastMessage: 'Thanks for the update 👍',
    time: '1h',
    online: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    avatar: 'SC',
    lastMessage: 'Can we reschedule?',
    time: '3h',
    unread: 1,
    online: false,
  },
];