export const mockContacts = [
  {
    id: "c1",
    name: "User1",
    avatar: "U1",
    lastMessage: "See you at the meeting!",
    time: "2m",
    unread: 2,
    online: true,
  },
  {
    id: "c2",
    name: "Another User",
    avatar: "AU",
    lastMessage: "Thanks for the update 👍",
    time: "1h",
    unread: 0,
    online: true,
  },
  {
    id: "c3",
    name: "Sarah Chen",
    avatar: "SC",
    lastMessage: "Can we reschedule?",
    time: "3h",
    unread: 1,
    online: false,
  },
  {
    id: "c4",
    name: "Marcus Rodriguez",
    avatar: "MR",
    lastMessage: "Perfect! I'll send it over.",
    time: "5h",
    unread: 0,
    online: true,
  },
  {
    id: "c5",
    name: "Emily Watson",
    avatar: "EW",
    lastMessage: "Great work on the presentation",
    time: "1d",
    unread: 0,
    online: false,
  },
  {
    id: "c6",
    name: "David Kim",
    avatar: "DK",
    lastMessage: "Let me check and get back to you",
    time: "1d",
    unread: 0,
    online: false,
  },
  {
    id: "c7",
    name: "Lisa Anderson",
    avatar: "LA",
    lastMessage: "Sure thing!",
    time: "2d",
    unread: 0,
    online: true,
  },
  {
    id: "c8",
    name: "James Taylor",
    avatar: "JT",
    lastMessage: "Looking forward to it",
    time: "3d",
    unread: 0,
    online: false,
  },
];
